Repository openstack-k8s-operators/openstack-ansibleee-operator, pull requests merged in 2022-12, with the labels that each got.

#26 Replace example with examples in README
  README.md
Labels: approved, lgtm, needs-ok-to-test

#28 Override maxDescLen for install and deploy
  Makefile
Labels: approved, lgtm

#27 Better examples, better README and removed the configs functionality
  README.md
  api/bases/redhat.com_ansibleees.yaml
  api/v1alpha1/ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/redhat.com_ansibleees.yaml
  controllers/ansibleee_controller.go
  examples/ansibleee-extravolumes.yaml
  examples/ansibleee-extravolumes_2_secrets.yaml
  examples/ansibleee-play.yaml
  examples/ansibleee-playbook-local.yaml
  examples/ansibleee-playbook.yaml
  examples/ansibleee-role.yaml
  examples/inventory-configmap.yaml
  examples/swift-configmap.yaml
  examples/test-configmap-1.yaml
  examples/test-configmap-2.yaml
Labels: approved, lgtm

#30 Update Makefile and add missing dependencies
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#31 Update actions/checkout and actions/setup-go to v3
  .github/workflows/build-ansibleee-operator.yaml
  .github/workflows/golangci-lint.yaml
  .github/workflows/release-ansibleee-operator.yaml
Labels: ok-to-test, approved, lgtm

#29 Support OwnNamespace installMode
  config/manifests/bases/ansibleee-operator.clusterserviceversion.yaml
Labels: ok-to-test, approved, lgtm
