Repository openstack-k8s-operators/openstack-ansibleee-operator, pull requests merged in 2022-11, with the labels that each got.

#19 More flexible way of executing standalone roles
  api/bases/redhat.com_ansibleees.yaml
  api/v1alpha1/ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/redhat.com_ansibleees.yaml
  controllers/ansibleee_controller.go
  examples/ansibleee-playbook.yaml
  examples/ansibleee-role.yaml
  examples/build.sh
Labels: approved, lgtm

#20 Pass the inventory as env variable instead of mounting a ConfigMap
  config/rbac/role.yaml
  controllers/ansibleee_controller.go
  examples/ansibleee-role.yaml
Labels: approved, lgtm

#21 cleanup play resource definitions and add quay image for playbook.yaml
  api/bases/redhat.com_ansibleees.yaml
  config/crd/bases/redhat.com_ansibleees.yaml
  examples/ansibleee-play.yaml
Labels: approved, lgtm, needs-ok-to-test

#22 dev: moved image back to triple-ansibleee
  examples/ansibleee-play.yaml
Labels: lgtm, needs-ok-to-test

#23 Reduce in one the number of needed env variables
  api/bases/redhat.com_ansibleees.yaml
  api/v1alpha1/ansibleee_types.go
  config/crd/bases/redhat.com_ansibleees.yaml
  controllers/ansibleee_controller.go
Labels: approved

#24 Add the stable tag to all the examples to use a stable version of the…
  examples/ansibleee-playbook-local.yaml
  examples/ansibleee-playbook.yaml
  examples/ansibleee-role.yaml
Labels: approved, lgtm
