Repository openstack-k8s-operators/openstack-ansibleee-operator, pull requests merged in 2023-01, with the labels that each got.

#41 Adding mkdocs and automate CR fields documentation
  .github/workflows/docs
  .gitignore
  Makefile
  docs/ansibleee.md
  docs/contributing.md
  docs/doc_requirements.txt
  docs/index.md
  mkdocs.yml
Labels: ok-to-test, approved, lgtm

#42 Fix docs workflow
  .github/workflows/docs.yaml
Labels: ok-to-test, approved, lgtm

#43 Document Using ansibleee-operator with TripleO Ansible
  README.md
Labels: approved, lgtm

#44 Add openstack logo
  .gitignore
  README.md
  docs/images/openstack-logo.png
  mkdocs.yml
Labels: approved, lgtm, needs-ok-to-test

#47 Revert "Bump k8s.io/api from 0.25.4 to 0.26.0"
  go.mod
  go.sum
Labels: approved, lgtm

#48 Not Openshit anymore
  README.md
Labels: approved

#49 Minor changes
  .github/create_bundle.sh
  .github/workflows/build-ansibleee-operator.yaml
  Makefile
  config/manager/kustomization.yaml
  examples/build.sh
Labels: approved, lgtm, needs-ok-to-test

#50 Rename ansibleee-operator to openstack-ansibleee-operator
  .github/create_bundle.sh
  .github/workflows/build-openstack-ansibleee-operator.yaml
  .github/workflows/release-openstack-ansibleee-operator.yaml
  Makefile
  PROJECT
  README.md
  api/bases/redhat.com_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/redhat.com_openstackansibleees.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/manifests/bases/openstack-ansibleee-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/rbac/role.yaml
  config/samples/_v1alpha1_ansibleee.yaml
  controllers/openstack_ansibleee_controller.go
  docs/openstack_ansibleee.md
  examples/build.sh
  examples/openstack-ansibleee-extravolumes.yaml
  examples/openstack-ansibleee-extravolumes_2_secrets.yaml
  examples/openstack-ansibleee-play.yaml
  examples/openstack-ansibleee-playbook-local.yaml
  examples/openstack-ansibleee-playbook.yaml
  examples/openstack-ansibleee-role.yaml
  main.go
  mkdocs.yml
Labels: approved, lgtm

#55 Update OWNERS file
  OWNERS
Labels: approved, lgtm

#52 Renaming github and quay repos
  .github/create_bundle.sh
  .github/workflows/build-openstack-ansibleee-operator.yaml
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/go.mod
  config/manifests/bases/openstack-ansibleee-operator.clusterserviceversion.yaml
  controllers/openstack_ansibleee_controller.go
  examples/build-remote.sh
  go.mod
  main.go
  mkdocs.yml
Labels: approved, lgtm

#53 tripleo-ansible-ee Dockerfile
  Makefile
  ansibleee/Dockerfile
  ansibleee/requirements.yaml
  ansibleee/settings
  ansibleee/tripleo_entrypoint.sh
Labels: approved, lgtm

#54 Removed nodes variable from status since it's not used
  api/bases/redhat.com_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/redhat.com_openstackansibleees.yaml
  docs/openstack_ansibleee.md
Labels: approved, lgtm

#56 Follow the openstack group pattern
  PROJECT
  README.md
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/v1alpha1/groupversion_info.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_ansibleees.yaml
  config/crd/patches/webhook_in_ansibleees.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/openstack-ansibleee-operator.clusterserviceversion.yaml
  config/rbac/ansibleee_editor_role.yaml
  config/rbac/ansibleee_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/_v1alpha1_ansibleee.yaml
  controllers/openstack_ansibleee_controller.go
  examples/build.sh
  examples/openstack-ansibleee-extravolumes.yaml
  examples/openstack-ansibleee-extravolumes_2_secrets.yaml
  examples/openstack-ansibleee-play.yaml
  examples/openstack-ansibleee-playbook-local.yaml
  examples/openstack-ansibleee-playbook.yaml
  examples/openstack-ansibleee-role.yaml
  main.go
Labels: approved, lgtm

#58 Add CodeQL workflow to find security vulnerabilities
  .github/workflows/codeql.yml
Labels: approved, lgtm

#62 Switch from tripleo-ansible to edpm-ansible repo
  ansibleee/Dockerfile
  ansibleee/edpm_entrypoint.sh
  ansibleee/requirements.yaml
Labels: approved, lgtm

#63 Added docker-push-ee flag to Makefile
  .github/workflows/build-openstack-ansibleee-operator.yaml
  Makefile
  ansibleee/Dockerfile
Labels: approved, lgtm

#64 Add pre-commit
  .github/create_bundle.sh
  .github/create_opm_index.sh
  .pre-commit-config.yaml
Labels: approved, lgtm

#67 Fix pre-commit issues
  ansibleee/edpm_entrypoint.sh
  examples/ceph-secret-example.yaml
  examples/ceph-secret-example2.yaml
  examples/inventory-configmap.yaml
  examples/openstack-ansibleee-extravolumes.yaml
  examples/openstack-ansibleee-play.yaml
  examples/openstack-ansibleee-role.yaml
  go.mod
  hack/boilerplate.go.txt
Labels: approved, lgtm

#69 Add support for building ee image using local edpm-ansible repo
  Makefile
  ansibleee/Dockerfile
Labels: ok-to-test, approved, lgtm

#65 Upgrade to golang 1.19/SDK 1.26
  .github/workflows/build-openstack-ansibleee-operator.yaml
  .github/workflows/golangci-lint.yaml
  Dockerfile
  Makefile
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/go.mod
  api/go.sum
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  examples/build-remote.sh
  go.mod
Labels: approved, lgtm

#70 Provide additional label to identify the operator
  config/manager/manager.yaml
Labels: approved, lgtm
