Repository openstack-k8s-operators/openstack-ansibleee-operator, pull requests merged in 2023-02, with the labels that each got.

#73 Adding ansible module
  ansible/inventory.go
  ansible/inventory_test.go
Labels: approved, lgtm

#72 Use LogForObject and LogErrorForObject from lib-common
  controllers/openstack_ansibleee_controller.go
  go.mod
  go.sum
Labels: approved, lgtm

#71 Removing deprecated go-lint
  .pre-commit-config.yaml
Labels: ok-to-test, approved, lgtm

#77 Change default values for strategy and Image spec fields and fixed docs and examples.
  README.md
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  examples/openstack-ansibleee-play.yaml
  examples/openstack-ansibleee-playbook.yaml
  examples/openstack-ansibleee-role.yaml
Labels: approved, lgtm

#76 Remove ansibleee-runner-code as we removed this code into edpm-ansibl…
  .github/workflows/build-openstack-ansibleee-operator.yaml
  ansibleee/Dockerfile
  ansibleee/edpm_entrypoint.sh
  ansibleee/requirements.yaml
  ansibleee/settings
Labels: ok-to-test, approved, lgtm

#78 Handle nill helper for OpenStackAnsibleEE
  controllers/openstack_ansibleee_controller.go
Labels: approved, lgtm

#79 Initialize Log in reconciler setup
  main.go
Labels: approved, lgtm

#80 Initialize kclient
  main.go
Labels: approved, lgtm

#81 Add build_root image configuration for prow
  .ci-operator.yaml
Labels: approved, lgtm

#82 Pass GITHUB_TOKEN to install_kustomize.sh to avoid rate-limit
  .github/workflows/build-openstack-ansibleee-operator.yaml
Labels: approved, lgtm

#85 Drop paths-ignore from build operator workflow
  .github/workflows/build-openstack-ansibleee-operator.yaml
Labels: approved, lgtm

#90 Fix CI dependencies issue
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: approved, lgtm

#88 Adding fields to Role and Task
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  docs/openstack_ansibleee.md
Labels: approved

#89 Remove ansible module
  ansible/inventory.go
  ansible/inventory_test.go
Labels: approved, lgtm

#94 Fix yaml markers
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  docs/openstack_ansibleee.md
Labels: approved, lgtm

#93 Allow attaching service pods to additional networks
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/go.mod
  api/go.sum
  api/v1alpha1/openstack_ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  config/manifests/bases/openstack-ansibleee-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/openstack_ansibleee_controller.go
  docs/openstack_ansibleee.md
  go.mod
  go.sum
  main.go
Labels: approved, lgtm

#95 Change Task Vars to be []string
  api/bases/ansibleee.openstack.org_openstackansibleees.yaml
  api/v1alpha1/openstack_ansibleee_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/ansibleee.openstack.org_openstackansibleees.yaml
  docs/openstack_ansibleee.md
Labels: approved, lgtm
